import 'package:muslim_data_flutter/muslim_data_flutter.dart';

class AppCity {
  final int id;
  final String nameAr;
  final String nameEn;
  final String countryAr;
  final String countryEn;
  final String countryCode;
  final double latitude;
  final double longitude;
  final String region;
  final List<String> searchKeywords;

  const AppCity({
    required this.id,
    required this.nameAr,
    required this.nameEn,
    required this.countryAr,
    required this.countryEn,
    required this.countryCode,
    required this.latitude,
    required this.longitude,
    required this.region,
    this.searchKeywords = const [],
  });

  Location toLocation() {
    return Location(
      id: id,
      name: nameAr,
      latitude: latitude,
      longitude: longitude,
      countryCode: countryCode,
      countryName: countryAr,
      hasFixedPrayerTime: false,
    );
  }
}

class LocationDataHelper {
  /// Regions for filtering
  static const List<String> regions = [
    'الكل',
    'مصر',
    'السعودية',
    'فلسطين والشام',
    'الخليج العربي',
    'العراق واليمن',
    'شمال إفريقيا',
    'عالمية وإسلامية',
  ];

  /// Search and filter cities
  static List<AppCity> searchCities({
    required String query,
    String selectedRegion = 'الكل',
  }) =>
      LocationArabicHelper.searchCities(
        query: query,
        selectedRegion: selectedRegion,
      );

  /// Comprehensive list of curated cities in Arabic
  static const List<AppCity> allCities = [
    // ==================== مصر (27 محافظة وأهم المدن) ====================
    AppCity(
      id: 1,
      nameAr: 'القاهرة',
      nameEn: 'Cairo',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 30.0444,
      longitude: 31.2357,
      region: 'مصر',
      searchKeywords: ['القاهره', 'cairo', 'العاصمة', 'مصر'],
    ),
    AppCity(
      id: 2,
      nameAr: 'الجيزة',
      nameEn: 'Giza',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 30.0131,
      longitude: 31.2089,
      region: 'مصر',
      searchKeywords: ['الجيزه', 'giza', 'الهرم', 'الأهرامات', 'الدقي', 'المهندسين'],
    ),
    AppCity(
      id: 3,
      nameAr: 'الإسكندرية',
      nameEn: 'Alexandria',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 31.2001,
      longitude: 29.9187,
      region: 'مصر',
      searchKeywords: ['الاسكندرية', 'الاسكندريه', 'الإسكندريه', 'alexandria', 'alex', 'عروس البحر'],
    ),
    AppCity(
      id: 4,
      nameAr: 'بورسعيد',
      nameEn: 'Port Said',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 31.2653,
      longitude: 32.3019,
      region: 'مصر',
      searchKeywords: ['بور سعيد', 'port said'],
    ),
    AppCity(
      id: 5,
      nameAr: 'السويس',
      nameEn: 'Suez',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 29.9668,
      longitude: 32.5498,
      region: 'مصر',
      searchKeywords: ['سويس', 'suez', 'قناة السويس'],
    ),
    AppCity(
      id: 6,
      nameAr: 'الإسماعيلية',
      nameEn: 'Ismailia',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 30.5965,
      longitude: 32.2715,
      region: 'مصر',
      searchKeywords: ['الاسماعيلية', 'الاسماعيليه', 'الإسماعيليه', 'ismailia'],
    ),
    AppCity(
      id: 7,
      nameAr: 'المنصورة (الدقهلية)',
      nameEn: 'Mansoura',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 31.0409,
      longitude: 31.3785,
      region: 'مصر',
      searchKeywords: ['المنصورة', 'المنصوره', 'الدقهلية', 'الدقهليه', 'mansoura'],
    ),
    AppCity(
      id: 8,
      nameAr: 'طنطا (الغربية)',
      nameEn: 'Tanta',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 30.7865,
      longitude: 31.0004,
      region: 'مصر',
      searchKeywords: ['طنطا', 'الغربية', 'الغربيه', 'tanta'],
    ),
    AppCity(
      id: 9,
      nameAr: 'المحلة الكبرى',
      nameEn: 'El Mahalla El Kubra',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 30.9706,
      longitude: 31.1669,
      region: 'مصر',
      searchKeywords: ['المحله الكبرى', 'المحله', 'المحلة', 'mahalla'],
    ),
    AppCity(
      id: 10,
      nameAr: 'الزقازيق (الشرقية)',
      nameEn: 'Zagazig',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 30.5765,
      longitude: 31.5041,
      region: 'مصر',
      searchKeywords: ['الزقازيق', 'الشرقية', 'الشرقيه', 'zagazig'],
    ),
    AppCity(
      id: 11,
      nameAr: 'العاشر من رمضان',
      nameEn: '10th of Ramadan',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 30.3040,
      longitude: 31.7431,
      region: 'مصر',
      searchKeywords: ['العاشر', '10th of ramadan'],
    ),
    AppCity(
      id: 12,
      nameAr: 'بنها (القليوبية)',
      nameEn: 'Banha',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 30.4660,
      longitude: 31.1856,
      region: 'مصر',
      searchKeywords: ['بنها', 'القليوبية', 'القليوبيه', 'banha', 'benha'],
    ),
    AppCity(
      id: 13,
      nameAr: 'شبين الكوم (المنوفية)',
      nameEn: 'Shibin El Kom',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 30.5567,
      longitude: 31.0118,
      region: 'مصر',
      searchKeywords: ['شبين الكوم', 'المنوفية', 'المنوفيه', 'shibin', 'menoufia'],
    ),
    AppCity(
      id: 14,
      nameAr: 'دمنهور (البحيرة)',
      nameEn: 'Damanhour',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 31.0409,
      longitude: 30.4700,
      region: 'مصر',
      searchKeywords: ['دمنهور', 'البحيرة', 'البحيره', 'damanhour'],
    ),
    AppCity(
      id: 15,
      nameAr: 'كفر الشيخ',
      nameEn: 'Kafr El Sheikh',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 31.1107,
      longitude: 30.9388,
      region: 'مصر',
      searchKeywords: ['كفرالشيخ', 'كفر الشيخ', 'kafr el sheikh'],
    ),
    AppCity(
      id: 16,
      nameAr: 'دمياط',
      nameEn: 'Damietta',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 31.4175,
      longitude: 31.8144,
      region: 'مصر',
      searchKeywords: ['دمياط', 'راس البر', 'رأس البر', 'damietta'],
    ),
    AppCity(
      id: 17,
      nameAr: 'الفيوم',
      nameEn: 'Fayoum',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 29.3084,
      longitude: 30.8428,
      region: 'مصر',
      searchKeywords: ['الفيوم', 'fayoum', 'faiyum'],
    ),
    AppCity(
      id: 18,
      nameAr: 'بني سويف',
      nameEn: 'Beni Suef',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 29.0661,
      longitude: 31.0994,
      region: 'مصر',
      searchKeywords: ['بني سويف', 'بنى سويف', 'beni suef'],
    ),
    AppCity(
      id: 19,
      nameAr: 'المنيا',
      nameEn: 'Minya',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 28.0871,
      longitude: 30.7618,
      region: 'مصر',
      searchKeywords: ['المنيا', 'عروس الصعيد', 'minya', 'menia'],
    ),
    AppCity(
      id: 20,
      nameAr: 'أسيوط',
      nameEn: 'Asyut',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 27.1783,
      longitude: 31.1859,
      region: 'مصر',
      searchKeywords: ['اسيوط', 'أسيوط', 'asyut', 'assiut'],
    ),
    AppCity(
      id: 21,
      nameAr: 'سوهاج',
      nameEn: 'Sohag',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 26.5569,
      longitude: 31.6948,
      region: 'مصر',
      searchKeywords: ['سوهاج', 'اخميم', 'جرجا', 'sohag'],
    ),
    AppCity(
      id: 22,
      nameAr: 'قنا',
      nameEn: 'Qena',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 26.1551,
      longitude: 32.7160,
      region: 'مصر',
      searchKeywords: ['قنا', 'نجع حمادي', 'qena'],
    ),
    AppCity(
      id: 23,
      nameAr: 'الأقصر',
      nameEn: 'Luxor',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 25.6872,
      longitude: 32.6396,
      region: 'مصر',
      searchKeywords: ['الاقصر', 'الأقصر', 'luxor'],
    ),
    AppCity(
      id: 24,
      nameAr: 'أسوان',
      nameEn: 'Aswan',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 24.0889,
      longitude: 32.8998,
      region: 'مصر',
      searchKeywords: ['اسوان', 'أسوان', 'النوبة', 'aswan'],
    ),
    AppCity(
      id: 25,
      nameAr: 'الغردقة (البحر الأحمر)',
      nameEn: 'Hurghada',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 27.2579,
      longitude: 33.8116,
      region: 'مصر',
      searchKeywords: ['الغردقة', 'الغردقه', 'البحر الاحمر', 'الجونة', 'hurghada'],
    ),
    AppCity(
      id: 26,
      nameAr: 'شرم الشيخ (جنوب سيناء)',
      nameEn: 'Sharm El Sheikh',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 27.9158,
      longitude: 34.3299,
      region: 'مصر',
      searchKeywords: ['شرم الشيخ', 'جنوب سيناء', 'دهب', 'sharm', 'sharm el sheikh'],
    ),
    AppCity(
      id: 27,
      nameAr: 'العريش (شمال سيناء)',
      nameEn: 'Arish',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 31.1316,
      longitude: 33.7984,
      region: 'مصر',
      searchKeywords: ['العريش', 'شمال سيناء', 'سيناء', 'arish'],
    ),
    AppCity(
      id: 28,
      nameAr: 'مرسى مطروح',
      nameEn: 'Marsa Matruh',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 31.3543,
      longitude: 27.2373,
      region: 'مصر',
      searchKeywords: ['مطروح', 'مرسى مطروح', 'مرسى مطروح', 'matruh'],
    ),
    AppCity(
      id: 29,
      nameAr: 'الخارجة (الوادي الجديد)',
      nameEn: 'Kharga',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 25.4514,
      longitude: 30.5463,
      region: 'مصر',
      searchKeywords: ['الخارجة', 'الخارجه', 'الوادي الجديد', 'kharga'],
    ),
    AppCity(
      id: 30,
      nameAr: 'مدينة 6 أكتوبر',
      nameEn: '6th of October',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 29.9870,
      longitude: 30.9515,
      region: 'مصر',
      searchKeywords: ['اكتوبر', 'أكتوبر', 'زايد', 'الشيخ زايد', 'october'],
    ),
    AppCity(
      id: 31,
      nameAr: 'العلمين الجديدة',
      nameEn: 'New Alamein',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 30.8358,
      longitude: 28.9567,
      region: 'مصر',
      searchKeywords: ['العلمين', 'الساحل الشمالي', 'alamein'],
    ),
    AppCity(
      id: 32,
      nameAr: 'كفر الدوار',
      nameEn: 'Kafr El Dawwar',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 31.1328,
      longitude: 30.1303,
      region: 'مصر',
      searchKeywords: ['كفر الدوار', 'kafr el dawwar'],
    ),
    AppCity(
      id: 33,
      nameAr: 'ميت غمر',
      nameEn: 'Mit Ghamr',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 30.7192,
      longitude: 31.2625,
      region: 'مصر',
      searchKeywords: ['ميت غمر', 'mit ghamr'],
    ),
    AppCity(
      id: 34,
      nameAr: 'إدفو',
      nameEn: 'Edfu',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 24.9781,
      longitude: 32.8753,
      region: 'مصر',
      searchKeywords: ['ادفو', 'إدفو', 'edfu'],
    ),
    AppCity(
      id: 35,
      nameAr: 'سيوة',
      nameEn: 'Siwa',
      countryAr: 'مصر',
      countryEn: 'Egypt',
      countryCode: 'EG',
      latitude: 29.2032,
      longitude: 25.5195,
      region: 'مصر',
      searchKeywords: ['سيوه', 'واحة سيوة', 'siwa'],
    ),

    // ==================== المملكة العربية السعودية ====================
    AppCity(
      id: 36,
      nameAr: 'مكة المكرمة',
      nameEn: 'Makkah',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 21.4225,
      longitude: 39.8262,
      region: 'السعودية',
      searchKeywords: ['مكه', 'مكة', 'الحرم', 'الكعبة', 'makkah', 'mecca', 'saudi'],
    ),
    AppCity(
      id: 37,
      nameAr: 'المدينة المنورة',
      nameEn: 'Madinah',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 24.5247,
      longitude: 39.5692,
      region: 'السعودية',
      searchKeywords: ['المدينه', 'طيبة', 'الحرم النبوي', 'madinah', 'medina'],
    ),
    AppCity(
      id: 38,
      nameAr: 'الرياض',
      nameEn: 'Riyadh',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 24.7136,
      longitude: 46.6753,
      region: 'السعودية',
      searchKeywords: ['الرياض', 'العاصمة', 'riyadh'],
    ),
    AppCity(
      id: 39,
      nameAr: 'جدة',
      nameEn: 'Jeddah',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 21.5433,
      longitude: 39.1728,
      region: 'السعودية',
      searchKeywords: ['جده', 'جدة', 'jeddah', 'jiddah'],
    ),
    AppCity(
      id: 40,
      nameAr: 'الدمام',
      nameEn: 'Dammam',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 26.4207,
      longitude: 50.0888,
      region: 'السعودية',
      searchKeywords: ['الدمام', 'الشرقية', 'dammam'],
    ),
    AppCity(
      id: 41,
      nameAr: 'الخبر',
      nameEn: 'Khobar',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 26.2172,
      longitude: 50.1971,
      region: 'السعودية',
      searchKeywords: ['الخبر', 'khobar', 'al khobar'],
    ),
    AppCity(
      id: 42,
      nameAr: 'الطائف',
      nameEn: 'Taif',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 21.2854,
      longitude: 40.4222,
      region: 'السعودية',
      searchKeywords: ['الطائف', 'الهدا', 'الشفا', 'taif'],
    ),
    AppCity(
      id: 43,
      nameAr: 'تبوك',
      nameEn: 'Tabuk',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 28.3835,
      longitude: 36.5662,
      region: 'السعودية',
      searchKeywords: ['تبوك', 'نيوم', 'tabuk'],
    ),
    AppCity(
      id: 44,
      nameAr: 'بريدة (القصيم)',
      nameEn: 'Buraidah',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 26.3260,
      longitude: 43.9750,
      region: 'السعودية',
      searchKeywords: ['بريدة', 'بريده', 'القصيم', 'buraidah'],
    ),
    AppCity(
      id: 45,
      nameAr: 'عنيزة (القصيم)',
      nameEn: 'Unaizah',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 26.0843,
      longitude: 43.9934,
      region: 'السعودية',
      searchKeywords: ['عنيزة', 'عنيزه', 'القصيم', 'unaizah'],
    ),
    AppCity(
      id: 46,
      nameAr: 'أبها (عسير)',
      nameEn: 'Abha',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 18.2164,
      longitude: 42.5053,
      region: 'السعودية',
      searchKeywords: ['ابها', 'أبها', 'عسير', 'abha'],
    ),
    AppCity(
      id: 47,
      nameAr: 'خميس مشيط',
      nameEn: 'Khamis Mushait',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 18.3000,
      longitude: 42.7333,
      region: 'السعودية',
      searchKeywords: ['خميس مشيط', 'khamis'],
    ),
    AppCity(
      id: 48,
      nameAr: 'حائل',
      nameEn: 'Hail',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 27.5114,
      longitude: 41.7208,
      region: 'السعودية',
      searchKeywords: ['حائل', 'عروس الشمال', 'hail'],
    ),
    AppCity(
      id: 49,
      nameAr: 'نجران',
      nameEn: 'Najran',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 17.4924,
      longitude: 44.1277,
      region: 'السعودية',
      searchKeywords: ['نجران', 'najran'],
    ),
    AppCity(
      id: 50,
      nameAr: 'جازان',
      nameEn: 'Jazan',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 16.8894,
      longitude: 42.5511,
      region: 'السعودية',
      searchKeywords: ['جازان', 'جيزان', 'jazan'],
    ),
    AppCity(
      id: 51,
      nameAr: 'الجبيل',
      nameEn: 'Jubail',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 27.0046,
      longitude: 49.6603,
      region: 'السعودية',
      searchKeywords: ['الجبيل', 'jubail'],
    ),
    AppCity(
      id: 52,
      nameAr: 'ينبع',
      nameEn: 'Yanbu',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 24.0891,
      longitude: 38.0637,
      region: 'السعودية',
      searchKeywords: ['ينبع', 'ينبع البحر', 'yanbu'],
    ),
    AppCity(
      id: 53,
      nameAr: 'حفر الباطن',
      nameEn: 'Hafar Al-Batin',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 28.4328,
      longitude: 45.9708,
      region: 'السعودية',
      searchKeywords: ['حفر الباطن', 'hafar al batin'],
    ),
    AppCity(
      id: 54,
      nameAr: 'الأحساء (الهفوف)',
      nameEn: 'Al Ahsa',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 25.3835,
      longitude: 49.5864,
      region: 'السعودية',
      searchKeywords: ['الاحساء', 'الأحساء', 'الهفوف', 'al ahsa', 'hofuf'],
    ),
    AppCity(
      id: 55,
      nameAr: 'القطيف',
      nameEn: 'Qatif',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 26.5196,
      longitude: 50.0135,
      region: 'السعودية',
      searchKeywords: ['القطيف', 'سيهات', 'qatif'],
    ),
    AppCity(
      id: 56,
      nameAr: 'سكاكا (الجوف)',
      nameEn: 'Sakaka',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 29.9697,
      longitude: 40.2064,
      region: 'السعودية',
      searchKeywords: ['سكاكا', 'الجوف', 'sakaka'],
    ),
    AppCity(
      id: 57,
      nameAr: 'عرعر (الحدود الشمالية)',
      nameEn: 'Arar',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 30.9753,
      longitude: 41.0381,
      region: 'السعودية',
      searchKeywords: ['عرعر', 'الحدود الشمالية', 'arar'],
    ),
    AppCity(
      id: 58,
      nameAr: 'الباحة',
      nameEn: 'Al Bahah',
      countryAr: 'المملكة العربية السعودية',
      countryEn: 'Saudi Arabia',
      countryCode: 'SA',
      latitude: 20.0129,
      longitude: 41.4677,
      region: 'السعودية',
      searchKeywords: ['الباحة', 'الباحه', 'al bahah'],
    ),

    // ==================== فلسطين وبلاد الشام ====================
    AppCity(
      id: 59,
      nameAr: 'القدس الشريف',
      nameEn: 'Jerusalem',
      countryAr: 'فلسطين',
      countryEn: 'Palestine',
      countryCode: 'PS',
      latitude: 31.7683,
      longitude: 35.2137,
      region: 'فلسطين والشام',
      searchKeywords: ['القدس', 'المسجد الاقصى', 'الأقصى', 'قبة الصخرة', 'jerusalem', 'palestine'],
    ),
    AppCity(
      id: 60,
      nameAr: 'غزة',
      nameEn: 'Gaza',
      countryAr: 'فلسطين',
      countryEn: 'Palestine',
      countryCode: 'PS',
      latitude: 31.5017,
      longitude: 34.4668,
      region: 'فلسطين والشام',
      searchKeywords: ['غزه', 'غزة العزة', 'قطاع غزة', 'gaza'],
    ),
    AppCity(
      id: 61,
      nameAr: 'الخليل',
      nameEn: 'Hebron',
      countryAr: 'فلسطين',
      countryEn: 'Palestine',
      countryCode: 'PS',
      latitude: 31.5293,
      longitude: 35.0938,
      region: 'فلسطين والشام',
      searchKeywords: ['الخليل', 'المسجد الإبراهيمي', 'hebron'],
    ),
    AppCity(
      id: 62,
      nameAr: 'نابلس',
      nameEn: 'Nablus',
      countryAr: 'فلسطين',
      countryEn: 'Palestine',
      countryCode: 'PS',
      latitude: 32.2211,
      longitude: 35.2544,
      region: 'فلسطين والشام',
      searchKeywords: ['نابلس', 'جبل النار', 'nablus'],
    ),
    AppCity(
      id: 63,
      nameAr: 'رام الله',
      nameEn: 'Ramallah',
      countryAr: 'فلسطين',
      countryEn: 'Palestine',
      countryCode: 'PS',
      latitude: 31.9038,
      longitude: 35.2034,
      region: 'فلسطين والشام',
      searchKeywords: ['رام الله', 'البيرة', 'ramallah'],
    ),
    AppCity(
      id: 64,
      nameAr: 'جنين',
      nameEn: 'Jenin',
      countryAr: 'فلسطين',
      countryEn: 'Palestine',
      countryCode: 'PS',
      latitude: 32.4646,
      longitude: 35.2957,
      region: 'فلسطين والشام',
      searchKeywords: ['جنين', 'jenin'],
    ),
    AppCity(
      id: 65,
      nameAr: 'خان يونس',
      nameEn: 'Khan Yunis',
      countryAr: 'فلسطين',
      countryEn: 'Palestine',
      countryCode: 'PS',
      latitude: 31.3462,
      longitude: 34.3063,
      region: 'فلسطين والشام',
      searchKeywords: ['خان يونس', 'khan yunis'],
    ),
    AppCity(
      id: 66,
      nameAr: 'رفح',
      nameEn: 'Rafah',
      countryAr: 'فلسطين',
      countryEn: 'Palestine',
      countryCode: 'PS',
      latitude: 31.2968,
      longitude: 34.2455,
      region: 'فلسطين والشام',
      searchKeywords: ['رفح', 'rafah'],
    ),
    AppCity(
      id: 67,
      nameAr: 'عمّان',
      nameEn: 'Amman',
      countryAr: 'الأردن',
      countryEn: 'Jordan',
      countryCode: 'JO',
      latitude: 31.9539,
      longitude: 35.9106,
      region: 'فلسطين والشام',
      searchKeywords: ['عمان', 'عمّان', 'الأردن', 'الاردن', 'amman', 'jordan'],
    ),
    AppCity(
      id: 68,
      nameAr: 'إربد',
      nameEn: 'Irbid',
      countryAr: 'الأردن',
      countryEn: 'Jordan',
      countryCode: 'JO',
      latitude: 32.5568,
      longitude: 35.8469,
      region: 'فلسطين والشام',
      searchKeywords: ['اربد', 'إربد', 'عروس الشمال', 'irbid'],
    ),
    AppCity(
      id: 69,
      nameAr: 'الزرقاء',
      nameEn: 'Zarqa',
      countryAr: 'الأردن',
      countryEn: 'Jordan',
      countryCode: 'JO',
      latitude: 32.0728,
      longitude: 36.0880,
      region: 'فلسطين والشام',
      searchKeywords: ['الزرقاء', 'الزرقا', 'zarqa'],
    ),
    AppCity(
      id: 70,
      nameAr: 'العقبة',
      nameEn: 'Aqaba',
      countryAr: 'الأردن',
      countryEn: 'Jordan',
      countryCode: 'JO',
      latitude: 29.5321,
      longitude: 35.0063,
      region: 'فلسطين والشام',
      searchKeywords: ['العقبة', 'العقبه', 'aqaba'],
    ),
    AppCity(
      id: 71,
      nameAr: 'دمشق',
      nameEn: 'Damascus',
      countryAr: 'سوريا',
      countryEn: 'Syria',
      countryCode: 'SY',
      latitude: 33.5138,
      longitude: 36.2765,
      region: 'فلسطين والشام',
      searchKeywords: ['دمشق', 'الشام', 'سوريا', 'damascus', 'syria'],
    ),
    AppCity(
      id: 72,
      nameAr: 'حلب',
      nameEn: 'Aleppo',
      countryAr: 'سوريا',
      countryEn: 'Syria',
      countryCode: 'SY',
      latitude: 36.2021,
      longitude: 37.1343,
      region: 'فلسطين والشام',
      searchKeywords: ['حلب', 'شهباء', 'aleppo'],
    ),
    AppCity(
      id: 73,
      nameAr: 'حمص',
      nameEn: 'Homs',
      countryAr: 'سوريا',
      countryEn: 'Syria',
      countryCode: 'SY',
      latitude: 34.7324,
      longitude: 36.7137,
      region: 'فلسطين والشام',
      searchKeywords: ['حمص', 'ابن الوليد', 'homs'],
    ),
    AppCity(
      id: 74,
      nameAr: 'حماة',
      nameEn: 'Hama',
      countryAr: 'سوريا',
      countryEn: 'Syria',
      countryCode: 'SY',
      latitude: 35.1318,
      longitude: 36.7578,
      region: 'فلسطين والشام',
      searchKeywords: ['حماة', 'حماه', 'النواعير', 'hama'],
    ),
    AppCity(
      id: 75,
      nameAr: 'اللاذقية',
      nameEn: 'Latakia',
      countryAr: 'سوريا',
      countryEn: 'Syria',
      countryCode: 'SY',
      latitude: 35.5317,
      longitude: 35.7900,
      region: 'فلسطين والشام',
      searchKeywords: ['اللاذقية', 'اللاذقيه', 'latakia'],
    ),
    AppCity(
      id: 76,
      nameAr: 'بيروت',
      nameEn: 'Beirut',
      countryAr: 'لبنان',
      countryEn: 'Lebanon',
      countryCode: 'LB',
      latitude: 33.8938,
      longitude: 35.5018,
      region: 'فلسطين والشام',
      searchKeywords: ['بيروت', 'لبنان', 'beirut', 'lebanon'],
    ),
    AppCity(
      id: 77,
      nameAr: 'طرابلس (لبنان)',
      nameEn: 'Tripoli Lebanon',
      countryAr: 'لبنان',
      countryEn: 'Lebanon',
      countryCode: 'LB',
      latitude: 34.4367,
      longitude: 35.8497,
      region: 'فلسطين والشام',
      searchKeywords: ['طرابلس لبنان', 'tripoli lebanon'],
    ),
    AppCity(
      id: 78,
      nameAr: 'صيدا',
      nameEn: 'Sidon',
      countryAr: 'لبنان',
      countryEn: 'Lebanon',
      countryCode: 'LB',
      latitude: 33.5631,
      longitude: 35.3689,
      region: 'فلسطين والشام',
      searchKeywords: ['صيدا', 'sidon', 'saida'],
    ),

    // ==================== الخليج العربي ====================
    AppCity(
      id: 79,
      nameAr: 'دبي',
      nameEn: 'Dubai',
      countryAr: 'الإمارات العربية المتحدة',
      countryEn: 'United Arab Emirates',
      countryCode: 'AE',
      latitude: 25.2048,
      longitude: 55.2708,
      region: 'الخليج العربي',
      searchKeywords: ['دبي', 'الامارات', 'الإمارات', 'dubai', 'uae'],
    ),
    AppCity(
      id: 80,
      nameAr: 'أبوظبي',
      nameEn: 'Abu Dhabi',
      countryAr: 'الإمارات العربية المتحدة',
      countryEn: 'United Arab Emirates',
      countryCode: 'AE',
      latitude: 24.4539,
      longitude: 54.3773,
      region: 'الخليج العربي',
      searchKeywords: ['ابوظبي', 'أبو ظبي', 'العاصمة', 'abu dhabi'],
    ),
    AppCity(
      id: 81,
      nameAr: 'الشارقة',
      nameEn: 'Sharjah',
      countryAr: 'الإمارات العربية المتحدة',
      countryEn: 'United Arab Emirates',
      countryCode: 'AE',
      latitude: 25.3463,
      longitude: 55.4209,
      region: 'الخليج العربي',
      searchKeywords: ['الشارقة', 'الشارقه', 'sharjah'],
    ),
    AppCity(
      id: 82,
      nameAr: 'عجمان',
      nameEn: 'Ajman',
      countryAr: 'الإمارات العربية المتحدة',
      countryEn: 'United Arab Emirates',
      countryCode: 'AE',
      latitude: 25.4052,
      longitude: 55.5136,
      region: 'الخليج العربي',
      searchKeywords: ['عجمان', 'ajman'],
    ),
    AppCity(
      id: 83,
      nameAr: 'رأس الخيمة',
      nameEn: 'Ras Al Khaimah',
      countryAr: 'الإمارات العربية المتحدة',
      countryEn: 'United Arab Emirates',
      countryCode: 'AE',
      latitude: 25.7895,
      longitude: 55.9432,
      region: 'الخليج العربي',
      searchKeywords: ['راس الخيمة', 'رأس الخيمه', 'ras al khaimah'],
    ),
    AppCity(
      id: 84,
      nameAr: 'العين',
      nameEn: 'Al Ain',
      countryAr: 'الإمارات العربية المتحدة',
      countryEn: 'United Arab Emirates',
      countryCode: 'AE',
      latitude: 24.2075,
      longitude: 55.7447,
      region: 'الخليج العربي',
      searchKeywords: ['العين', 'مدينة العين', 'al ain'],
    ),
    AppCity(
      id: 85,
      nameAr: 'الفجيرة',
      nameEn: 'Fujairah',
      countryAr: 'الإمارات العربية المتحدة',
      countryEn: 'United Arab Emirates',
      countryCode: 'AE',
      latitude: 25.1288,
      longitude: 56.3265,
      region: 'الخليج العربي',
      searchKeywords: ['الفجيرة', 'الفجيره', 'fujairah'],
    ),
    AppCity(
      id: 86,
      nameAr: 'الدوحة',
      nameEn: 'Doha',
      countryAr: 'قطر',
      countryEn: 'Qatar',
      countryCode: 'QA',
      latitude: 25.2854,
      longitude: 51.5310,
      region: 'الخليج العربي',
      searchKeywords: ['الدوحة', 'الدوحه', 'قطر', 'doha', 'qatar'],
    ),
    AppCity(
      id: 87,
      nameAr: 'الريان',
      nameEn: 'Al Rayyan',
      countryAr: 'قطر',
      countryEn: 'Qatar',
      countryCode: 'QA',
      latitude: 25.2919,
      longitude: 51.4244,
      region: 'الخليج العربي',
      searchKeywords: ['الريان', 'al rayyan'],
    ),
    AppCity(
      id: 88,
      nameAr: 'مدينة الكويت',
      nameEn: 'Kuwait City',
      countryAr: 'الكويت',
      countryEn: 'Kuwait',
      countryCode: 'KW',
      latitude: 29.3759,
      longitude: 47.9774,
      region: 'الخليج العربي',
      searchKeywords: ['الكويت', 'مدينة الكويت', 'كويت', 'kuwait'],
    ),
    AppCity(
      id: 89,
      nameAr: 'حولي',
      nameEn: 'Hawally',
      countryAr: 'الكويت',
      countryEn: 'Kuwait',
      countryCode: 'KW',
      latitude: 29.3328,
      longitude: 48.0283,
      region: 'الخليج العربي',
      searchKeywords: ['حولي', 'hawally'],
    ),
    AppCity(
      id: 90,
      nameAr: 'الأحمدي',
      nameEn: 'Al Ahmadi',
      countryAr: 'الكويت',
      countryEn: 'Kuwait',
      countryCode: 'KW',
      latitude: 29.0769,
      longitude: 48.0839,
      region: 'الخليج العربي',
      searchKeywords: ['الاحمدي', 'الأحمدي', 'ahmadi'],
    ),
    AppCity(
      id: 91,
      nameAr: 'المنامة',
      nameEn: 'Manama',
      countryAr: 'البحرين',
      countryEn: 'Bahrain',
      countryCode: 'BH',
      latitude: 26.2285,
      longitude: 50.5860,
      region: 'الخليج العربي',
      searchKeywords: ['المنامة', 'المنامه', 'البحرين', 'manama', 'bahrain'],
    ),
    AppCity(
      id: 92,
      nameAr: 'المحرق',
      nameEn: 'Muharraq',
      countryAr: 'البحرين',
      countryEn: 'Bahrain',
      countryCode: 'BH',
      latitude: 26.2572,
      longitude: 50.6119,
      region: 'الخليج العربي',
      searchKeywords: ['المحرق', 'muharraq'],
    ),
    AppCity(
      id: 93,
      nameAr: 'مسقط',
      nameEn: 'Muscat',
      countryAr: 'سلطنة عُمان',
      countryEn: 'Oman',
      countryCode: 'OM',
      latitude: 23.5880,
      longitude: 58.3829,
      region: 'الخليج العربي',
      searchKeywords: ['مسقط', 'عمان', 'عُمان', 'سلطنة عمان', 'muscat', 'oman'],
    ),
    AppCity(
      id: 94,
      nameAr: 'صلالة',
      nameEn: 'Salalah',
      countryAr: 'سلطنة عُمان',
      countryEn: 'Oman',
      countryCode: 'OM',
      latitude: 17.0151,
      longitude: 54.0924,
      region: 'الخليج العربي',
      searchKeywords: ['صلالة', 'صلاله', 'ظفار', 'salalah'],
    ),
    AppCity(
      id: 95,
      nameAr: 'صحار',
      nameEn: 'Sohar',
      countryAr: 'سلطنة عُمان',
      countryEn: 'Oman',
      countryCode: 'OM',
      latitude: 24.3461,
      longitude: 56.7075,
      region: 'الخليج العربي',
      searchKeywords: ['صحار', 'sohar'],
    ),

    // ==================== العراق واليمن ====================
    AppCity(
      id: 96,
      nameAr: 'بغداد',
      nameEn: 'Baghdad',
      countryAr: 'العراق',
      countryEn: 'Iraq',
      countryCode: 'IQ',
      latitude: 33.3152,
      longitude: 44.3661,
      region: 'العراق واليمن',
      searchKeywords: ['بغداد', 'دار السلام', 'العراق', 'baghdad', 'iraq'],
    ),
    AppCity(
      id: 97,
      nameAr: 'البصرة',
      nameEn: 'Basra',
      countryAr: 'العراق',
      countryEn: 'Iraq',
      countryCode: 'IQ',
      latitude: 30.5081,
      longitude: 47.7835,
      region: 'العراق واليمن',
      searchKeywords: ['البصرة', 'البصره', 'شط العرب', 'basra'],
    ),
    AppCity(
      id: 98,
      nameAr: 'الموصل',
      nameEn: 'Mosul',
      countryAr: 'العراق',
      countryEn: 'Iraq',
      countryCode: 'IQ',
      latitude: 36.3400,
      longitude: 43.1300,
      region: 'العراق واليمن',
      searchKeywords: ['الموصل', 'نينوى', 'mosul'],
    ),
    AppCity(
      id: 99,
      nameAr: 'أربيل',
      nameEn: 'Erbil',
      countryAr: 'العراق',
      countryEn: 'Iraq',
      countryCode: 'IQ',
      latitude: 36.1901,
      longitude: 43.9930,
      region: 'العراق واليمن',
      searchKeywords: ['اربيل', 'أربيل', 'كردستان', 'erbil'],
    ),
    AppCity(
      id: 100,
      nameAr: 'النجف الأشرف',
      nameEn: 'Najaf',
      countryAr: 'العراق',
      countryEn: 'Iraq',
      countryCode: 'IQ',
      latitude: 32.0000,
      longitude: 44.3333,
      region: 'العراق واليمن',
      searchKeywords: ['النجف', 'النجف الاشرف', 'najaf'],
    ),
    AppCity(
      id: 101,
      nameAr: 'كربلاء المقدسة',
      nameEn: 'Karbala',
      countryAr: 'العراق',
      countryEn: 'Iraq',
      countryCode: 'IQ',
      latitude: 32.6160,
      longitude: 44.0249,
      region: 'العراق واليمن',
      searchKeywords: ['كربلاء', 'كربلاء المقدسه', 'karbala'],
    ),
    AppCity(
      id: 102,
      nameAr: 'كركوك',
      nameEn: 'Kirkuk',
      countryAr: 'العراق',
      countryEn: 'Iraq',
      countryCode: 'IQ',
      latitude: 35.4681,
      longitude: 44.3922,
      region: 'العراق واليمن',
      searchKeywords: ['كركوك', 'kirkuk'],
    ),
    AppCity(
      id: 103,
      nameAr: 'السليمانية',
      nameEn: 'Sulaymaniyah',
      countryAr: 'العراق',
      countryEn: 'Iraq',
      countryCode: 'IQ',
      latitude: 35.5558,
      longitude: 45.4351,
      region: 'العراق واليمن',
      searchKeywords: ['السليمانية', 'السليمانيه', 'sulaymaniyah'],
    ),
    AppCity(
      id: 104,
      nameAr: 'صنعاء',
      nameEn: 'Sanaa',
      countryAr: 'اليمن',
      countryEn: 'Yemen',
      countryCode: 'YE',
      latitude: 15.3694,
      longitude: 44.1910,
      region: 'العراق واليمن',
      searchKeywords: ['صنعاء', 'اليمن', 'sanaa', 'yemen'],
    ),
    AppCity(
      id: 105,
      nameAr: 'عدن',
      nameEn: 'Aden',
      countryAr: 'اليمن',
      countryEn: 'Yemen',
      countryCode: 'YE',
      latitude: 12.7855,
      longitude: 45.0187,
      region: 'العراق واليمن',
      searchKeywords: ['عدن', 'aden'],
    ),
    AppCity(
      id: 106,
      nameAr: 'تعز',
      nameEn: 'Taiz',
      countryAr: 'اليمن',
      countryEn: 'Yemen',
      countryCode: 'YE',
      latitude: 13.5795,
      longitude: 44.0209,
      region: 'العراق واليمن',
      searchKeywords: ['تعز', 'taiz'],
    ),
    AppCity(
      id: 107,
      nameAr: 'الحديدة',
      nameEn: 'Hodeidah',
      countryAr: 'اليمن',
      countryEn: 'Yemen',
      countryCode: 'YE',
      latitude: 14.7978,
      longitude: 42.9545,
      region: 'العراق واليمن',
      searchKeywords: ['الحديدة', 'الحديده', 'hodeidah'],
    ),
    AppCity(
      id: 108,
      nameAr: 'المكلا (حضرموت)',
      nameEn: 'Mukalla',
      countryAr: 'اليمن',
      countryEn: 'Yemen',
      countryCode: 'YE',
      latitude: 14.5425,
      longitude: 49.1242,
      region: 'العراق واليمن',
      searchKeywords: ['المكلا', 'حضرموت', 'mukalla'],
    ),

    // ==================== شمال إفريقيا والسودان ====================
    AppCity(
      id: 109,
      nameAr: 'الخرطوم',
      nameEn: 'Khartoum',
      countryAr: 'السودان',
      countryEn: 'Sudan',
      countryCode: 'SD',
      latitude: 15.5007,
      longitude: 32.5599,
      region: 'شمال إفريقيا',
      searchKeywords: ['الخرطوم', 'السودان', 'khartoum', 'sudan'],
    ),
    AppCity(
      id: 110,
      nameAr: 'أم درمان',
      nameEn: 'Omdurman',
      countryAr: 'السودان',
      countryEn: 'Sudan',
      countryCode: 'SD',
      latitude: 15.6500,
      longitude: 32.4833,
      region: 'شمال إفريقيا',
      searchKeywords: ['ام درمان', 'أم درمان', 'omdurman'],
    ),
    AppCity(
      id: 111,
      nameAr: 'بورتسودان',
      nameEn: 'Port Sudan',
      countryAr: 'السودان',
      countryEn: 'Sudan',
      countryCode: 'SD',
      latitude: 19.6175,
      longitude: 37.2164,
      region: 'شمال إفريقيا',
      searchKeywords: ['بورتسودان', 'بورسودان', 'port sudan'],
    ),
    AppCity(
      id: 112,
      nameAr: 'طرابلس (ليبيا)',
      nameEn: 'Tripoli Libya',
      countryAr: 'ليبيا',
      countryEn: 'Libya',
      countryCode: 'LY',
      latitude: 32.8872,
      longitude: 13.1913,
      region: 'شمال إفريقيا',
      searchKeywords: ['طرابلس ليبيا', 'ليبيا', 'tripoli libya', 'libya'],
    ),
    AppCity(
      id: 113,
      nameAr: 'بنغازي',
      nameEn: 'Benghazi',
      countryAr: 'ليبيا',
      countryEn: 'Libya',
      countryCode: 'LY',
      latitude: 32.1167,
      longitude: 20.0667,
      region: 'شمال إفريقيا',
      searchKeywords: ['بنغازي', 'benghazi'],
    ),
    AppCity(
      id: 114,
      nameAr: 'مصراتة',
      nameEn: 'Misrata',
      countryAr: 'ليبيا',
      countryEn: 'Libya',
      countryCode: 'LY',
      latitude: 32.3754,
      longitude: 15.0925,
      region: 'شمال إفريقيا',
      searchKeywords: ['مصراتة', 'مصراته', 'misrata'],
    ),
    AppCity(
      id: 115,
      nameAr: 'تونس العاصمة',
      nameEn: 'Tunis',
      countryAr: 'تونس',
      countryEn: 'Tunisia',
      countryCode: 'TN',
      latitude: 36.8065,
      longitude: 10.1815,
      region: 'شمال إفريقيا',
      searchKeywords: ['تونس', 'تونس العاصمة', 'tunis', 'tunisia'],
    ),
    AppCity(
      id: 116,
      nameAr: 'صفاقس',
      nameEn: 'Sfax',
      countryAr: 'تونس',
      countryEn: 'Tunisia',
      countryCode: 'TN',
      latitude: 34.7406,
      longitude: 10.7603,
      region: 'شمال إفريقيا',
      searchKeywords: ['صفاقس', 'sfax'],
    ),
    AppCity(
      id: 117,
      nameAr: 'سوسة',
      nameEn: 'Sousse',
      countryAr: 'تونس',
      countryEn: 'Tunisia',
      countryCode: 'TN',
      latitude: 35.8256,
      longitude: 10.6369,
      region: 'شمال إفريقيا',
      searchKeywords: ['سوسة', 'سوسه', 'sousse'],
    ),
    AppCity(
      id: 118,
      nameAr: 'القيروان',
      nameEn: 'Kairouan',
      countryAr: 'تونس',
      countryEn: 'Tunisia',
      countryCode: 'TN',
      latitude: 35.6781,
      longitude: 10.0963,
      region: 'شمال إفريقيا',
      searchKeywords: ['القيروان', 'عاصمة الاغالبة', 'kairouan'],
    ),
    AppCity(
      id: 119,
      nameAr: 'الجزائر العاصمة',
      nameEn: 'Algiers',
      countryAr: 'الجزائر',
      countryEn: 'Algeria',
      countryCode: 'DZ',
      latitude: 36.7538,
      longitude: 3.0588,
      region: 'شمال إفريقيا',
      searchKeywords: ['الجزائر', 'الجزائر العاصمة', 'algiers', 'algeria'],
    ),
    AppCity(
      id: 120,
      nameAr: 'وهران',
      nameEn: 'Oran',
      countryAr: 'الجزائر',
      countryEn: 'Algeria',
      countryCode: 'DZ',
      latitude: 35.6987,
      longitude: -0.6349,
      region: 'شمال إفريقيا',
      searchKeywords: ['وهران', 'الباهية', 'oran'],
    ),
    AppCity(
      id: 121,
      nameAr: 'قسنطينة',
      nameEn: 'Constantine',
      countryAr: 'الجزائر',
      countryEn: 'Algeria',
      countryCode: 'DZ',
      latitude: 36.3650,
      longitude: 6.6147,
      region: 'شمال إفريقيا',
      searchKeywords: ['قسنطينة', 'قسنطينه', 'مدينة الجسور', 'constantine'],
    ),
    AppCity(
      id: 122,
      nameAr: 'الرباط',
      nameEn: 'Rabat',
      countryAr: 'المملكة المغربية',
      countryEn: 'Morocco',
      countryCode: 'MA',
      latitude: 34.0209,
      longitude: -6.8416,
      region: 'شمال إفريقيا',
      searchKeywords: ['الرباط', 'المغرب', 'rabat', 'morocco'],
    ),
    AppCity(
      id: 123,
      nameAr: 'الدار البيضاء (كازابلانكا)',
      nameEn: 'Casablanca',
      countryAr: 'المملكة المغربية',
      countryEn: 'Morocco',
      countryCode: 'MA',
      latitude: 33.5731,
      longitude: -7.5898,
      region: 'شمال إفريقيا',
      searchKeywords: ['الدار البيضاء', 'كازا', 'كازابلانكا', 'casablanca', 'casa'],
    ),
    AppCity(
      id: 124,
      nameAr: 'مراكش',
      nameEn: 'Marrakech',
      countryAr: 'المملكة المغربية',
      countryEn: 'Morocco',
      countryCode: 'MA',
      latitude: 31.6295,
      longitude: -7.9811,
      region: 'شمال إفريقيا',
      searchKeywords: ['مراكش', 'المدينة الحمراء', 'marrakech'],
    ),
    AppCity(
      id: 125,
      nameAr: 'فاس',
      nameEn: 'Fez',
      countryAr: 'المملكة المغربية',
      countryEn: 'Morocco',
      countryCode: 'MA',
      latitude: 34.0181,
      longitude: -5.0078,
      region: 'شمال إفريقيا',
      searchKeywords: ['فاس', 'العاصمة العلمية', 'fez', 'fes'],
    ),
    AppCity(
      id: 126,
      nameAr: 'طنجة',
      nameEn: 'Tangier',
      countryAr: 'المملكة المغربية',
      countryEn: 'Morocco',
      countryCode: 'MA',
      latitude: 35.7595,
      longitude: -5.8340,
      region: 'شمال إفريقيا',
      searchKeywords: ['طنجة', 'طنجه', 'عروس الشمال', 'tangier'],
    ),
    AppCity(
      id: 127,
      nameAr: 'نواكشوط',
      nameEn: 'Nouakchott',
      countryAr: 'موريتانيا',
      countryEn: 'Mauritania',
      countryCode: 'MR',
      latitude: 18.0735,
      longitude: -15.9582,
      region: 'شمال إفريقيا',
      searchKeywords: ['نواكشوط', 'موريتانيا', 'nouakchott', 'mauritania'],
    ),
    AppCity(
      id: 128,
      nameAr: 'مقديشو',
      nameEn: 'Mogadishu',
      countryAr: 'الصومال',
      countryEn: 'Somalia',
      countryCode: 'SO',
      latitude: 2.0469,
      longitude: 45.3182,
      region: 'شمال إفريقيا',
      searchKeywords: ['مقديشو', 'الصومال', 'mogadishu', 'somalia'],
    ),
    AppCity(
      id: 129,
      nameAr: 'جيبوتي',
      nameEn: 'Djibouti',
      countryAr: 'جيبوتي',
      countryEn: 'Djibouti',
      countryCode: 'DJ',
      latitude: 11.5721,
      longitude: 43.1456,
      region: 'شمال إفريقيا',
      searchKeywords: ['جيبوتي', 'djibouti'],
    ),

    // ==================== عواصم ومدن إسلامية وعالمية ====================
    AppCity(
      id: 130,
      nameAr: 'إسطنبول',
      nameEn: 'Istanbul',
      countryAr: 'تركيا',
      countryEn: 'Turkey',
      countryCode: 'TR',
      latitude: 41.0082,
      longitude: 28.9784,
      region: 'عالمية وإسلامية',
      searchKeywords: ['اسطنبول', 'إسطنبول', 'تركيا', 'istanbul', 'turkey'],
    ),
    AppCity(
      id: 131,
      nameAr: 'أنقرة',
      nameEn: 'Ankara',
      countryAr: 'تركيا',
      countryEn: 'Turkey',
      countryCode: 'TR',
      latitude: 39.9334,
      longitude: 32.8597,
      region: 'عالمية وإسلامية',
      searchKeywords: ['انقرة', 'أنقرة', 'ankara'],
    ),
    AppCity(
      id: 132,
      nameAr: 'جاكرتا',
      nameEn: 'Jakarta',
      countryAr: 'إندونيسيا',
      countryEn: 'Indonesia',
      countryCode: 'ID',
      latitude: -6.2088,
      longitude: 106.8456,
      region: 'عالمية وإسلامية',
      searchKeywords: ['جاكرتا', 'اندونيسيا', 'إندونيسيا', 'jakarta', 'indonesia'],
    ),
    AppCity(
      id: 133,
      nameAr: 'كوالالمبور',
      nameEn: 'Kuala Lumpur',
      countryAr: 'ماليزيا',
      countryEn: 'Malaysia',
      countryCode: 'MY',
      latitude: 3.1390,
      longitude: 101.6869,
      region: 'عالمية وإسلامية',
      searchKeywords: ['كوالالمبور', 'ماليزيا', 'kuala lumpur', 'malaysia'],
    ),
    AppCity(
      id: 134,
      nameAr: 'إسلام آباد',
      nameEn: 'Islamabad',
      countryAr: 'باكستان',
      countryEn: 'Pakistan',
      countryCode: 'PK',
      latitude: 33.6844,
      longitude: 73.0479,
      region: 'عالمية وإسلامية',
      searchKeywords: ['اسلام اباد', 'إسلام آباد', 'باكستان', 'islamabad', 'pakistan'],
    ),
    AppCity(
      id: 135,
      nameAr: 'كراتشي',
      nameEn: 'Karachi',
      countryAr: 'باكستان',
      countryEn: 'Pakistan',
      countryCode: 'PK',
      latitude: 24.8607,
      longitude: 67.0011,
      region: 'عالمية وإسلامية',
      searchKeywords: ['كراتشي', 'karachi'],
    ),
    AppCity(
      id: 136,
      nameAr: 'لاهور',
      nameEn: 'Lahore',
      countryAr: 'باكستان',
      countryEn: 'Pakistan',
      countryCode: 'PK',
      latitude: 31.5204,
      longitude: 74.3587,
      region: 'عالمية وإسلامية',
      searchKeywords: ['لاهور', 'lahore'],
    ),
    AppCity(
      id: 137,
      nameAr: 'دكا',
      nameEn: 'Dhaka',
      countryAr: 'بنغلاديش',
      countryEn: 'Bangladesh',
      countryCode: 'BD',
      latitude: 23.8103,
      longitude: 90.4125,
      region: 'عالمية وإسلامية',
      searchKeywords: ['دكا', 'بنغلاديش', 'dhaka', 'bangladesh'],
    ),
    AppCity(
      id: 138,
      nameAr: 'طشقند',
      nameEn: 'Tashkent',
      countryAr: 'أوزبكستان',
      countryEn: 'Uzbekistan',
      countryCode: 'UZ',
      latitude: 41.2995,
      longitude: 69.2401,
      region: 'عالمية وإسلامية',
      searchKeywords: ['طشقند', 'اوزبكستان', 'أوزبكستان', 'tashkent', 'uzbekistan'],
    ),
    AppCity(
      id: 139,
      nameAr: 'سمرقند',
      nameEn: 'Samarkand',
      countryAr: 'أوزبكستان',
      countryEn: 'Uzbekistan',
      countryCode: 'UZ',
      latitude: 39.6270,
      longitude: 66.9750,
      region: 'عالمية وإسلامية',
      searchKeywords: ['سمرقند', 'samarkand'],
    ),
    AppCity(
      id: 140,
      nameAr: 'بخارى',
      nameEn: 'Bukhara',
      countryAr: 'أوزبكستان',
      countryEn: 'Uzbekistan',
      countryCode: 'UZ',
      latitude: 39.7747,
      longitude: 64.4286,
      region: 'عالمية وإسلامية',
      searchKeywords: ['بخارى', 'الإمام البخاري', 'bukhara'],
    ),
    AppCity(
      id: 141,
      nameAr: 'باكو',
      nameEn: 'Baku',
      countryAr: 'أذربيجان',
      countryEn: 'Azerbaijan',
      countryCode: 'AZ',
      latitude: 40.4093,
      longitude: 49.8671,
      region: 'عالمية وإسلامية',
      searchKeywords: ['باكو', 'اذربيجان', 'أذربيجان', 'baku', 'azerbaijan'],
    ),
    AppCity(
      id: 142,
      nameAr: 'لندن',
      nameEn: 'London',
      countryAr: 'المملكة المتحدة',
      countryEn: 'United Kingdom',
      countryCode: 'GB',
      latitude: 51.5074,
      longitude: -0.1278,
      region: 'عالمية وإسلامية',
      searchKeywords: ['لندن', 'بريطانيا', 'انجلترا', 'london', 'uk'],
    ),
    AppCity(
      id: 143,
      nameAr: 'باريس',
      nameEn: 'Paris',
      countryAr: 'فرنسا',
      countryEn: 'France',
      countryCode: 'FR',
      latitude: 48.8566,
      longitude: 2.3522,
      region: 'عالمية وإسلامية',
      searchKeywords: ['باريس', 'فرنسا', 'paris', 'france'],
    ),
    AppCity(
      id: 144,
      nameAr: 'برلين',
      nameEn: 'Berlin',
      countryAr: 'ألمانيا',
      countryEn: 'Germany',
      countryCode: 'DE',
      latitude: 52.5200,
      longitude: 13.4050,
      region: 'عالمية وإسلامية',
      searchKeywords: ['برلين', 'المانيا', 'ألمانيا', 'berlin', 'germany'],
    ),
  ];
}

class LocationArabicHelper {
  /// Normalizes Arabic text to ease search comparisons:
  /// - Removes Tashkeel
  /// - Converts [أ, إ, آ] to [ا]
  /// - Converts [ة] to [ه]
  /// - Converts [ى] to [ي]
  static String normalizeArabic(String text) {
    var s = text.toLowerCase().trim();
    s = s.replaceAll(RegExp(r'[\u064B-\u0652]'), '');
    s = s.replaceAll(RegExp(r'[أإآ]'), 'ا');
    s = s.replaceAll('ة', 'ه');
    s = s.replaceAll('ى', 'ي');
    return s;
  }

  /// Dictionary of common English city names to Arabic
  static final Map<String, String> _cityDictionary = {
    'cairo': 'القاهرة',
    'giza': 'الجيزة',
    'alexandria': 'الإسكندرية',
    'port said': 'بورسعيد',
    'suez': 'السويس',
    'ismailia': 'الإسماعيلية',
    'mansoura': 'المنصورة',
    'tanta': 'طنطا',
    'zagazig': 'الزقازيق',
    'fayoum': 'الفيوم',
    'faiyum': 'الفيوم',
    'beni suef': 'بني سويف',
    'minya': 'المنيا',
    'asyut': 'أسيوط',
    'assiut': 'أسيوط',
    'sohag': 'سوهاج',
    'qena': 'قنا',
    'luxor': 'الأقصر',
    'aswan': 'أسوان',
    'hurghada': 'الغردقة',
    'sharm el sheikh': 'شرم الشيخ',
    'arish': 'العريش',
    'marsa matruh': 'مرسى مطروح',
    'damanhour': 'دمنهور',
    'damietta': 'دمياط',
    'kafr el sheikh': 'كفر الشيخ',
    'banha': 'بنها',
    'benha': 'بنها',
    'shibin el kom': 'شبين الكوم',
    'makkah': 'مكة المكرمة',
    'mecca': 'مكة المكرمة',
    'madinah': 'المدينة المنورة',
    'medina': 'المدينة المنورة',
    'riyadh': 'الرياض',
    'jeddah': 'جدة',
    'dammam': 'الدمام',
    'khobar': 'الخبر',
    'taif': 'الطائف',
    'tabuk': 'تبوك',
    'abha': 'أبها',
    'buraidah': 'بريدة',
    'unaizah': 'عنيزة',
    'hail': 'حائل',
    'najran': 'نجران',
    'jazan': 'جازان',
    'jubail': 'الجبيل',
    'yanbu': 'ينبع',
    'jerusalem': 'القدس الشريف',
    'al-quds': 'القدس الشريف',
    'gaza': 'غزة',
    'hebron': 'الخليل',
    'nablus': 'نابلس',
    'ramallah': 'رام الله',
    'amman': 'عمان',
    'damascus': 'دمشق',
    'aleppo': 'حلب',
    'beirut': 'بيروت',
    'dubai': 'دبي',
    'abu dhabi': 'أبوظبي',
    'sharjah': 'الشارقة',
    'ajman': 'عجمان',
    'doha': 'الدوحة',
    'kuwait': 'الكويت',
    'kuwait city': 'مدينة الكويت',
    'manama': 'المنامة',
    'muscat': 'مسقط',
    'baghdad': 'بغداد',
    'basra': 'البصرة',
    'mosul': 'الموصل',
    'erbil': 'أربيل',
    'najaf': 'النجف الأشرف',
    'karbala': 'كربلاء المقدسة',
    'sanaa': 'صنعاء',
    'aden': 'عدن',
    'khartoum': 'الخرطوم',
    'tripoli': 'طرابلس',
    'tunis': 'تونس العاصمة',
    'algiers': 'الجزائر العاصمة',
    'rabat': 'الرباط',
    'casablanca': 'الدار البيضاء',
    'istanbul': 'إسطنبول',
    'ankara': 'أنقرة',
    'jakarta': 'جاكرتا',
    'kuala lumpur': 'كوالالمبور',
    'islamabad': 'إسلام آباد',
    'karachi': 'كراتشي',
    'london': 'لندن',
    'paris': 'باريس',
    'berlin': 'برلين',
  };

  /// Dictionary of English country names and ISO codes to Arabic
  static final Map<String, String> _countryDictionary = {
    'egypt': 'مصر',
    'eg': 'مصر',
    'saudi arabia': 'المملكة العربية السعودية',
    'sa': 'المملكة العربية السعودية',
    'palestine': 'فلسطين',
    'ps': 'فلسطين',
    'jordan': 'الأردن',
    'jo': 'الأردن',
    'syria': 'سوريا',
    'sy': 'سوريا',
    'lebanon': 'لبنان',
    'lb': 'لبنان',
    'united arab emirates': 'الإمارات العربية المتحدة',
    'uae': 'الإمارات العربية المتحدة',
    'ae': 'الإمارات العربية المتحدة',
    'qatar': 'قطر',
    'qa': 'قطر',
    'kuwait': 'الكويت',
    'kw': 'الكويت',
    'bahrain': 'البحرين',
    'bh': 'البحرين',
    'oman': 'سلطنة عُمان',
    'om': 'سلطنة عُمان',
    'yemen': 'اليمن',
    'ye': 'اليمن',
    'iraq': 'العراق',
    'iq': 'العراق',
    'sudan': 'السودان',
    'sd': 'السودان',
    'libya': 'ليبيا',
    'ly': 'ليبيا',
    'tunisia': 'تونس',
    'tn': 'تونس',
    'algeria': 'الجزائر',
    'dz': 'الجزائر',
    'morocco': 'المملكة المغربية',
    'ma': 'المملكة المغربية',
    'mauritania': 'موريتانيا',
    'mr': 'موريتانيا',
    'somalia': 'الصومال',
    'so': 'الصومال',
    'djibouti': 'جيبوتي',
    'dj': 'جيبوتي',
    'turkey': 'تركيا',
    'tr': 'تركيا',
    'indonesia': 'إندونيسيا',
    'id': 'إندونيسيا',
    'malaysia': 'ماليزيا',
    'my': 'ماليزيا',
    'pakistan': 'باكستان',
    'pk': 'باكستان',
    'bangladesh': 'بنغلاديش',
    'bd': 'بنغلاديش',
    'uzbekistan': 'أوزبكستان',
    'uz': 'أوزبكستان',
    'azerbaijan': 'أذربيجان',
    'az': 'أذربيجان',
    'united kingdom': 'المملكة المتحدة',
    'uk': 'المملكة المتحدة',
    'gb': 'المملكة المتحدة',
    'france': 'فرنسا',
    'fr': 'فرنسا',
    'germany': 'ألمانيا',
    'de': 'ألمانيا',
  };

  /// Translates a city name to Arabic if an English name is provided
  static String toArabicCity(String cityName) {
    final trimmed = cityName.trim();
    if (trimmed.isEmpty) return trimmed;
    // If already contains Arabic characters, return as-is
    if (RegExp(r'[\u0600-\u06FF]').hasMatch(trimmed)) {
      return trimmed;
    }
    final lower = trimmed.toLowerCase();
    return _cityDictionary[lower] ?? trimmed;
  }

  /// Translates a country name/code to Arabic
  static String toArabicCountry(String countryName, [String countryCode = '']) {
    final trimmed = countryName.trim();
    if (trimmed.isNotEmpty && RegExp(r'[\u0600-\u06FF]').hasMatch(trimmed)) {
      return trimmed;
    }
    final lowerName = trimmed.toLowerCase();
    if (_countryDictionary.containsKey(lowerName)) {
      return _countryDictionary[lowerName]!;
    }
    final lowerCode = countryCode.trim().toLowerCase();
    if (_countryDictionary.containsKey(lowerCode)) {
      return _countryDictionary[lowerCode]!;
    }
    return trimmed.isNotEmpty ? trimmed : countryCode;
  }

  /// Converts any Location object into an Arabic-localized Location
  static Location toArabicLocation(Location loc) {
    return Location(
      id: loc.id,
      name: toArabicCity(loc.name),
      latitude: loc.latitude,
      longitude: loc.longitude,
      countryCode: loc.countryCode,
      countryName: toArabicCountry(loc.countryName, loc.countryCode),
      hasFixedPrayerTime: loc.hasFixedPrayerTime,
    );
  }

  /// Filter cities by search query and optional region
  static List<AppCity> searchCities({
    required String query,
    String selectedRegion = 'الكل',
  }) {
    var list = LocationDataHelper.allCities;

    if (selectedRegion != 'الكل') {
      list = list.where((c) => c.region == selectedRegion).toList();
    }

    final q = normalizeArabic(query);
    if (q.isEmpty) return list;

    final qTokens = q.split(' ').where((t) => t.isNotEmpty).toList();

    return list.where((city) {
      final normNameAr = normalizeArabic(city.nameAr);
      final normNameEn = normalizeArabic(city.nameEn);
      final normCountryAr = normalizeArabic(city.countryAr);
      final normCountryEn = normalizeArabic(city.countryEn);
      final normKeywords = city.searchKeywords.map(normalizeArabic).toList();

      final combined = '$normNameAr $normNameEn $normCountryAr $normCountryEn ${normKeywords.join(' ')}';

      return qTokens.every((token) => combined.contains(token));
    }).toList();
  }
}
